Repository LSSTDESC/gcr-catalogs, pull requests merged in 2018-11, with the labels that each got.

#213 change modifiers for cModel parameters
  GCRCatalogs/dc2_object.py
Labels: enhancement, reader

#228 object catalog reader now provides fallback schema
  GCRCatalogs/dc2_object.py
Labels: enhancement, reader, run1.2

#222 preparing for v0.9.2
  GCRCatalogs/version.py
Labels: run1.2

#230 add DPDD-only object catalog 1.2p
  GCRCatalogs/catalog_configs/dc2_object_run1.2p_dpdd_only.yaml
  GCRCatalogs/dc2_object.py
  README.md
Labels: configs, object-catalog, reader, run1.2

#233 Reader for v1.1.0, v1.1.3, and v1.1.4
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1.3.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1.3_image.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1.3_small.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1.4.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1.4_image.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1.4_small.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v1.1_small.yaml
  GCRCatalogs/cosmodc2.py
  README.md
Labels: configs

#232 add 1.2p object catalog
  GCRCatalogs/catalog_configs/dc2_object_run1.2p.yaml
  GCRCatalogs/catalog_configs/dc2_object_run1.2p_all_columns.yaml
  GCRCatalogs/catalog_configs/dc2_object_run1.2p_dpdd_only.yaml
  GCRCatalogs/catalog_configs/dc2_object_run1.2p_tract4850.yaml
  GCRCatalogs/dc2_object.py
  README.md
Labels: configs, run1.2

#238 Applying emissionLine
  GCRCatalogs/cosmodc2.py
Labels: reader
