Repository LSSTDESC/gcr-catalogs, pull requests merged in 2018-08, with the labels that each got.

#167 improve object catalog reader
  GCRCatalogs/dc2_object.py
Labels: enhancement, reader

#170 cache constant arrays for object catalog reader
  GCRCatalogs/dc2_object.py
Labels: enhancement, reader

#166 New experimental feature: composite catalog reader
  GCRCatalogs/alphaq_addon.py
  GCRCatalogs/catalog_configs/proto-dc2_v2.1.2_addon_knots.yaml
  GCRCatalogs/catalog_configs/proto-dc2_v2.1.2_addon_tidal.yaml
  GCRCatalogs/catalog_configs/proto-dc2_v3.0_addon_knots.yaml
  GCRCatalogs/catalog_configs/proto-dc2_v3.0_addon_redmapper.yaml
  GCRCatalogs/catalog_configs/proto-dc2_v4.3_addon_redmapper.yaml
  GCRCatalogs/catalog_configs/proto-dc2_v4.3_test.yaml
  GCRCatalogs/catalog_configs/protoDC2_addon_tidal.yaml
  GCRCatalogs/catalog_configs/um_v0.1_shear_test.yaml
  GCRCatalogs/catalog_configs/um_v0.1_test_shear.yaml
  GCRCatalogs/composite.py
  GCRCatalogs/version.py
  examples/CompositeReader example.ipynb
  setup.py
Labels: add-on, configs, enhancement, reader

#173 bug fix in the UMShearCatalog reader
  GCRCatalogs/cosmodc2.py
Labels: bug

#177 fix rebinning default behavior
  GCRCatalogs/catalog_configs/focal_plane_test.yaml
  GCRCatalogs/catalog_configs/focal_plane_test_rebin-16.yaml
  GCRCatalogs/focal_plane.py
Labels: bug, configs, reader

#174 add base_filters option to truth catalog reader
  GCRCatalogs/catalog_configs/dc2_run1.1_extragalactic_truth_match.yaml
  GCRCatalogs/catalog_configs/dc2_truth_run1.1_galaxies.yaml
  GCRCatalogs/dc2_truth.py
  GCRCatalogs/utils.py
Labels: configs, enhancement, reader

#178 Make rescale function call future compatible
  GCRCatalogs/focal_plane.py
Labels: enhancement, reader

#180 Changes for reader and config files for cosmoDC2 base and test catalogs
  GCRCatalogs/catalog_configs/baseDC2_v0.4.5.yaml
  GCRCatalogs/catalog_configs/baseDC2_v0.4.5_test.yaml
  GCRCatalogs/catalog_configs/cosmoDC2_v0.4_test.yaml
  GCRCatalogs/cosmodc2.py
Labels: configs, reader

#182 Update focal plane reader to accommodate Run 1.2i images
  GCRCatalogs/catalog_configs/dc2_eimages_run1.2i_visit-181898.yaml
  GCRCatalogs/catalog_configs/dc2_eimages_run1.2p_visit-181898.yaml
  GCRCatalogs/catalog_configs/focal_plane_test.yaml
  GCRCatalogs/catalog_configs/focal_plane_test_rebin-16.yaml
  GCRCatalogs/eimage.py
  GCRCatalogs/focal_plane.py
Labels: enhancement, reader
